name: Notificação
on: push
jobs:
  code-info:
    runs-on: ubuntu-latest
    steps:
      - name: Caminho da pasta
        run: pwd
      - name: Recuperar código
        uses: actions/checkout@v3
      - name: Listar arquivos
        run: ls -al
  mail:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar e-mail com detalhes
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_HOST}}
          server_port: ${{secrets.MAIL_PORT}}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Novo push
          to: dev01@tedsys.com.br
          from: TedSys
          body: 'Detalhes: ${{ toJSON(github.event) }}'
          ignore_cert: true